"""Graduation Quotes Module
A collection of 100 inspiring quotes for the BiT Class of 2026.
"""
import random
from datetime import date

class GraduationQuotes:
    QUOTES = [
        "Your time is limited, don't waste it living someone else's life. – Steve Jobs",
        "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
        "Education is the most powerful weapon which you can use to change the world. – Nelson Mandela",
        "The only impossible journey is the one you never begin. – Tony Robbins",
        "Success is not final, failure is not fatal: it is the courage to continue that counts. – Winston Churchill",
        "Don't let the noise of others' opinions drown out your own inner voice. – Steve Jobs",
        "The beautiful thing about learning is that no one can take it away from you. – B.B. King",
        "Go confidently in the direction of your dreams. Live the life you have imagined. – Henry David Thoreau",
        "The expert in anything was once a beginner. – Helen Hayes",
        "Believe you can and you're halfway there. – Theodore Roosevelt",
        "It always seems impossible until it's done. – Nelson Mandela",
        "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
        "The only way to do great work is to love what you do. – Steve Jobs",
        "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
        "The future depends on what you do today. – Mahatma Gandhi",
        "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
        "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
        "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
        "Life is 10% what happens to you and 90% how you react to it. – Charles R. Swindoll",
        "Change the world by being yourself. – Amy Poehler",
        "Every strike brings me closer to the next home run. – Babe Ruth",
        "Life is what happens when you're busy making other plans. – John Lennon",
        "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. – Henry Ford",
        "It's not whether you get knocked down, it's whether you get up. – Vince Lombardi",
        "Failure is the condiment that gives success its flavor. – Truman Capote",
        "Never let the fear of striking out keep you from playing the game. – Babe Ruth",
        "Life is trying things to see if they work. – Ray Bradbury",
        "Many of life's failures are people who did not realize how close they were to success when they gave up. – Thomas Edison",
        "You miss 100% of the shots you don't take. – Wayne Gretzky",
        "Whether you think you can or you think you can't, you're right. – Henry Ford",
        "I have learned over the years that when one's mind is made up, this diminishes fear. – Rosa Parks",
        "I alone cannot change the world, but I can cast a stone across the water to create many ripples. – Mother Teresa",
        "Nothing is impossible, the word itself says 'I'm possible'! – Audrey Hepburn",
        "The question isn't who is going to let me; it's who is going to stop me. – Ayn Rand",
        "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
        "It is during our darkest moments that we must focus to see the light. – Aristotle",
        "Don't judge each day by the harvest you reap but by the seeds that you plant. – Robert Louis Stevenson",
        "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
        "An unexamined life is not worth living. – Socrates",
        "Eighty percent of success is showing up. – Woody Allen",
        "Winning isn't everything, but wanting to win is. – Vince Lombardi",
        "I am not a product of my circumstances. I am a product of my decisions. – Stephen Covey",
        "Every child is an artist. The problem is how to remain an artist once he grows up. – Pablo Picasso",
        "You can never cross the ocean until you have the courage to lose sight of the shore. – Christopher Columbus",
        "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. – Maya Angelou",
        "Either you run the day, or the day runs you. – Jim Rohn",
        "The two most important days in your life are the day you are born and the day you find out why. – Mark Twain",
        "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it. – Johann Wolfgang von Goethe",
        "The best revenge is massive success. – Frank Sinatra",
        "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily. – Zig Ziglar",
        "Life shrinks or expands in proportion to one's courage. – Anais Nin",
        "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced. – Vincent Van Gogh",
        "There is only one way to avoid criticism: do nothing, say nothing, and be nothing. – Aristotle",
        "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you. – Jesus",
        "Build your own dreams, or someone else will hire you to build theirs. – Farrah Gray",
        "The battles that count aren't the ones for gold medals. The struggles within yourself are where the real victories lie. – Jesse Owens",
        "Education is not preparation for life; education is life itself. – John Dewey",
        "Your education is a dress rehearsal for a life that is yours to lead. – Nora Ephron",
        "The fireworks begin today. Each diploma is a lighted match. Each one of you is a fuse. – Edward Koch",
        "Don't be afraid to give up the good to go for the great. – John D. Rockefeller",
        "I find that the harder I work, the more luck I seem to have. – Thomas Jefferson",
        "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
        "The way to get started is to quit talking and begin doing. – Walt Disney",
        "If you really look closely, most overnight successes took a long time. – Steve Jobs",
        "The secret of success is to do the common thing uncommonly well. – John D. Rockefeller Jr.",
        "I never dreamed about success, I worked for it. – Estée Lauder",
        "Success seems to be connected with action. Successful people keep moving. – Conrad Hilton",
        "The road to success and the road to failure are almost exactly the same. – Colin R. Davis",
        "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
        "Try not to become a person of success, but rather try to become a person of value. – Albert Einstein",
        "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change. – Charles Darwin",
        "Great minds discuss ideas; average minds discuss events; small minds discuss people. – Eleanor Roosevelt",
        "I have not failed. I've just found 10,000 ways that won't work. – Thomas A. Edison",
        "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. – David Brinkley",
        "No one can make you feel inferior without your consent. – Eleanor Roosevelt",
        "The whole secret of a successful life is to find out what is one's destiny to do, and then do it. – Henry Ford",
        "If you're going through hell, keep going. – Winston Churchill",
        "If you want to lift yourself up, lift up someone else. – Booker T. Washington",
        "The more that you read, the more things you will know. The more that you learn, the more places you'll go. – Dr. Seuss",
        "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
        "Dream big and dare to fail. – Norman Vaughan",
        "Our lives begin to end the day we become silent about things that matter. – Martin Luther King Jr.",
        "The question isn't who is going to let me; it's who is going to stop me. – Ayn Rand",
        "Do one thing every day that scares you. – Eleanor Roosevelt",
        "It's not what you look at that matters, it's what you see. – Henry David Thoreau",
        "The purpose of our lives is to be happy. – Dalai Lama",
        "Life is really simple, but we insist on making it complicated. – Confucius",
        "You only live once, but if you do it right, once is enough. – Mae West",
        "In the end, it's not the years in your life that count. It's the life in your years. – Abraham Lincoln",
        "Everything you've ever wanted is on the other side of fear. – George Addair",
        "Don't wait. The time will never be just right. – Napoleon Hill",
        "If you can dream it, you can do it. – Walt Disney",
        "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
        "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
        "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
        "Action is the foundational key to all success. – Pablo Picasso",
        "Opportunity is missed by most people because it is dressed in overalls and looks like work. – Thomas Edison",
        "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
        "Be the change that you wish to see in the world. – Mahatma Gandhi",
        "Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential. – Kerry Washington"
    ]

    @classmethod
    def get_random_quote(cls):
        return random.choice(cls.QUOTES)

